const { app, BrowserWindow, protocol } = require('electron');
const path = require('path');
const serve = require('electron-serve');

// We use electron-serve to serve the Next.js static export using a custom scheme (app://)
// This fixes all absolute paths (/projects/aetherRead/...) generated by Next.js
const loadURL = serve({ directory: 'app', scheme: 'app' });

let mainWindow;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    icon: path.join(__dirname, 'icon.png'),
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      // Security: we don't enable nodeIntegration directly in renderer
      nodeIntegration: false,
      contextIsolation: true
    }
  });

  // Remove default menu bar for a cleaner app look
  mainWindow.setMenuBarVisibility(false);

  // Load the web app
  // electron-serve will map app://- to the 'app' directory
  // Next.js expects the basepath /projects/aetherRead, so we navigate there
  loadURL(mainWindow).then(() => {
    mainWindow.loadURL('app://-/projects/aetherRead/index.html').catch(() => {
      mainWindow.loadURL('app://-/index.html');
    });
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

// Intercept file requests if needed, but electron-serve handles app:// scheme
app.whenReady().then(() => {
  createWindow();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
    }
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});
